name: Java CI with Allure Report

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Install Allure Commandline
      run: brew install allure

    - name: Build with Maven
      run: mvn -B compile
    
    - name: Run Tests (Generating Allure Results)
      run: mvn verify # Ensure this matches your project's specifics

    - name: Execute the Runner Class
      run: mvn test -Dtest=CukesRunner.java

    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report
    
    # Add additional steps for linting or grammar checks as needed
    - name: Checkstyle analysis
      run: mvn checkstyle:checkstyle

